# Generated by Django 3.2 on 2022-04-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bnb_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='payeer_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='perfect_money_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usdt_erc20_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usdt_trc20_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='litecoin_address',
            field=models.CharField(blank=True, help_text='User LItecoin wallet address for payment', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stellar_address',
            field=models.CharField(blank=True, help_text='User Stellar wallet address for payment', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='adminwalletaddress',
            name='wallet_type',
            field=models.CharField(choices=[('BITCOIN', 'BITCOIN'), ('BITCOIN CASH', 'BITCOIN CASH'), ('ETHEREUM', 'ETHEREUM'), ('STELLAR', 'STELLAR'), ('LITECOIN', 'LITECOIN')], default='BITCOIN', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userearningrecord',
            name='percentage',
            field=models.CharField(default='1.9%', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='earning_rate',
            field=models.CharField(choices=[('1.9%', '1.9%'), ('2.8%', '2.8%'), ('3.9%', '3.9%'), ('5.5%', '5.5%')], default='1.9%', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_coin_paid',
            field=models.CharField(blank=True, choices=[('BITCOIN', 'BITCOIN'), ('BITCOIN CASH', 'BITCOIN CASH'), ('ETHEREUM', 'ETHEREUM'), ('STELLAR', 'STELLAR'), ('LITECOIN', 'LITECOIN')], default='BITCOIN', help_text='The coin selected by the user during the last payment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('TRILLER', 'TRILLER'), ('PRO', 'PRO'), ('EXPERT', 'EXPERT')], default='GENERAL', max_length=10),
        ),
    ]
